apiVersion: v1
entries:
  apollo-portal:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2021-02-17T22:07:45.831126+08:00"
    description: A Helm chart for Apollo Portal
    digest: 8a55c5f3ddd76b9768067fe6eecfb34b588084557c11882e263abb2af7dfc173
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-portal
    type: application
    urls:
    - apollo-portal-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.7.2
    created: "2021-02-17T22:07:45.830584+08:00"
    description: A Helm chart for Apollo Portal
    digest: 1db8b2435e0471ef55c63c47b970e4ae059800f88ed4ac4f1ca6cd27fe502722
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-portal
    type: application
    urls:
    - apollo-portal-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2021-02-17T22:07:45.82916+08:00"
    description: A Helm chart for Apollo Portal
    digest: 7c1b4efa13d4cc54a714b3ec836f609a8f97286c465789f6d807d1227cfc5b74
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-portal
    type: application
    urls:
    - apollo-portal-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2021-02-17T22:07:45.82834+08:00"
    description: A Helm chart for Apollo Portal
    digest: b838e4478f0c031093691defeffb5805d51189989db0eb9caaa2dc67905c8391
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-portal
    type: application
    urls:
    - apollo-portal-0.1.0.tgz
    version: 0.1.0
  apollo-service:
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2021-02-17T22:07:45.834585+08:00"
    description: A Helm chart for Apollo Config Service and Apollo Admin Service
    digest: 73e66c651499f93b6f3891e979dcbe2a20ad37809087e42bc98643c604c457c6
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-service
    type: application
    urls:
    - apollo-service-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.7.2
    created: "2021-02-17T22:07:45.833867+08:00"
    description: A Helm chart for Apollo Config Service and Apollo Admin Service
    digest: be9379611b45db416a32b7e1367527faec7c29a969493ca4a0a72b5b87a280f4
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-service
    type: application
    urls:
    - apollo-service-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2021-02-17T22:07:45.832945+08:00"
    description: A Helm chart for Apollo Config Service and Apollo Admin Service
    digest: 787a26590d68735341b7839c14274492097fed4a0843fc9a1e5c692194199707
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-service
    type: application
    urls:
    - apollo-service-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2021-02-17T22:07:45.832068+08:00"
    description: A Helm chart for Apollo Config Service and Apollo Admin Service
    digest: 65c08f39b54ad1ac1d849cc841ce978bd6e95b0b6cbd2423d9f17f66bc7e8d3e
    home: https://github.com/ctripcorp/apollo
    icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
    maintainers:
    - email: nobodyiam@gmail.com
      name: nobodyiam
      url: https://github.com/nobodyiam
    name: apollo-service
    type: application
    urls:
    - apollo-service-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-17T22:07:45.827123+08:00"
